services:
  mongodb:
    image: mongo:latest
    container_name: omics-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - omics-network

  backend:
    build: ./backend
    container_name: omics-backend
    ports:
      - "3001:3001"
    depends_on:
      - mongodb
    environment:
      - PORT=3001
      - MONGODB_URI=mongodb://mongodb:27017/omics
      - FRONTEND_URL=http://localhost:3000
    volumes:
      - ./simple_demo.tsv:/app/simple_demo.tsv
    networks:
      - omics-network

  frontend:
    build: ./frontend
    container_name: omics-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:3001/api
    networks:
      - omics-network

networks:
  omics-network:
    driver: bridge

volumes:
  mongodb_data: 